# -*- coding: utf-8 -*-
"""KMEANS_CLUSTERING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p9tBla8OxuNEXoWYVPZd11qdfwdcg2is
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv("/content/Mall_Customers.csv")

df

df.isnull().sum()

df.info()

df.loc[df['Genre'] == 'Male', 'Annual_Income_(k$)'].sum()

df.describe()

from sklearn.cluster import KMeans
wcss=[]
X = df[['Annual_Income_(k$)', 'Spending_Score']]
for i in range(1,11):
  kmeans = KMeans(n_clusters=i,init='k-means++',random_state=42, n_init=10)
  kmeans.fit(X)
  wcss.append(kmeans.inertia_)

plt.figure(figsize=(10,5))
plt.plot(range(1,11),wcss)
plt.title('The Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('wcss')

kmeans=KMeans(n_clusters=5,init='k-means++',random_state=42)
y_kmeans=kmeans.fit_predict(X)

kmeans.inertia_

kmeans.labels_

plt.figure(figsize=(10,5))
plt.scatter(X.iloc[y_kmeans==0,0],X.iloc[y_kmeans==0,1], color='red',s=10,label='cluster1')
plt.scatter(X.iloc[y_kmeans==1,0],X.iloc[y_kmeans==1,1], color='green',s=10,label='cluster2')
plt.scatter(X.iloc[y_kmeans==2,0],X.iloc[y_kmeans==2,1], color='blue',s=10,label='cluster3')
plt.scatter(X.iloc[y_kmeans==3,0],X.iloc[y_kmeans==3,1], color='yellow',s=10,label='cluster4')
plt.scatter(X.iloc[y_kmeans==4,0],X.iloc[y_kmeans==4,1], color='pink',s=10,label='cluster5')
plt.legend()
plt.show()

